version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: pwd12345678
      POSTGRES_DB: batch-data-crawler
    ports:
      - "5432:5432"
#     volumes:
#       - pg_data:/var/lib/postgresql/data

# volumes:
#   pg_data: